name: Validate Triple-T store files
# use it on your own project: https://github.com/TrianguloY/action-validate-Triple-T

on:
  # run this workflow on master branch push
  push:
    branches:
      - master
  # run this workflow on master pull requests
  pull_request:
    branches:
      - master

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Download project files
        uses: actions/checkout@v4

      - name: Validate Triple-T files
        uses: TrianguloY/action-validate-Triple-T@v1
        with:
          ignore: 'Changelog too large'
